version: '3.8'

services:
  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile.mongodb
    ports:
      - 27017:27017
  
  mongoimport:
    build:
      context: ./db
      dockerfile: Dockerfile.mongoimport
    depends_on:
      - mongodb

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
