version: "3.8"

services:
  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile.mongodb
      args:
        USERNAME: $DB_USERNAME
        PASSWORD: $DB_PASSWORD
    shm_size: 2gb
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile.postgres
      args:
        USERNAME: $DB_USERNAME
        PASSWORD: $DB_PASSWORD
    shm_size: 2gb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  mongo-data:
  postgres-data:
