version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        USERNAME: $DB_USERNAME
        PASSWORD: $DB_PASSWORD
        PORT: 8000
        MONGO_HOST: mongodb
        MONGO_PORT: 27017
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    depends_on:
      - mongodb
      - postgres
    ports:
      - $API_PORT:8000

  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile.mongodb
      args:
        USERNAME: $DB_USERNAME
        PASSWORD: $DB_PASSWORD
        API_HOST: api
        API_PORT: 8000
    shm_size: 1gb
    volumes:
      - mongo-data:/data/db
    ports:
      - $MONGO_PORT:27017

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile.postgres
      args:
        USERNAME: $DB_USERNAME
        PASSWORD: $DB_PASSWORD
        API_HOST: api
        API_PORT: 8000
    shm_size: 1gb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432

volumes:
  mongo-data:
  postgres-data:
