version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
  
  mongo-seed:
    build:
      context: ./seed/mongo
      dockerfile: Dockerfile

  postgres:
    build:
      context: ./seed/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
