FROM postgres:latest

ARG USERNAME
ARG PASSWORD

ENV POSTGRES_USER $USERNAME
ENV POSTGRES_PASSWORD $PASSWORD

RUN apt-get update && apt-get install -y curl

WORKDIR /seed

COPY ./seed/*.csv .
RUN chmod 777 *.csv
RUN chmod 777 ./

WORKDIR /docker-entrypoint-initdb.d

COPY init_postgres.sql .
COPY postinit.sh .

EXPOSE 5432
