FROM mongo:latest

ARG USERNAME
ARG PASSWORD

ENV MONGO_INITDB_ROOT_USERNAME $USERNAME
ENV MONGO_INITDB_ROOT_PASSWORD $PASSWORD

WORKDIR /seed

COPY ./seed/*.csv .
RUN chmod 777 *.csv
RUN chmod 777 ./

WORKDIR /docker-entrypoint-initdb.d

COPY init_mongo.sh .
COPY postinit.sh .

EXPOSE 27017
