FROM mongo:latest

ARG USERNAME
ARG PASSWORD
ARG API_HOST
ARG API_PORT

ENV MONGO_INITDB_ROOT_USERNAME $USERNAME
ENV MONGO_INITDB_ROOT_PASSWORD $PASSWORD
ENV API_HOST $API_HOST
ENV API_PORT $API_PORT

RUN apt-get update && apt-get install -y curl

WORKDIR /seed

COPY ./seed/*.csv .
RUN chmod 777 *.csv
RUN chmod 777 ./

WORKDIR /docker-entrypoint-initdb.d

COPY init_mongo.sh .
COPY postinit.sh .

EXPOSE 27017
